language: ruby
arch:
  - amd64
  - ppc64le
rvm:
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
matrix:
  allowed_failures:
    - rvm: ruby-head

before_install: gem update bundler
script: bundle exec rake spec
